### PR TITLE
Secure websocket

### PR DESCRIPTION
**Pull request by fabfurnari**
This is a very simple PR to allow client connections to secure websockets (wss).
Two boolean flags has been added, one (`-tls`) to change the protocol schema from `ws` to `wss` and one that allows insecure connections (`-insecure`) to unverified SSL certificates.

Some documentation about has been added too.

### CODE REVIEW

**Review by skx — APPROVED** [review]

**Comment by skx** [comment]
The code looks good, and I appreciated the documentation update.

The `-insecure` flag is fine.  But for the `-tls` flag I wonder if the simpler method isn't the better one?  If we instead allow the `-tunnel` argument to be a URL we could parse the protocol that way.

For example:

     tunneller -tunnel test.example.com    -> WS
     tunneller -tunnel ws://test.example.com    -> WS
     tunneller -tunnel wss://test.example.com    -> WSS

That means we don't have to add a new flag, which is one less thing to remember.     (We could even cheat and pretend the endpoint was "http" vs. "https" if we wanted.)

**Comment by fabfurnari** [comment]
That's even better!
I'll do some modification to the PR to parse full url.

**Comment by fabfurnari** [comment]
I've done some modifications in order to allow `ws://` `wss://` or no-prefix urls, please run some tests because don't know if it breaks something (it shouldn't)

**Comment by skx** [comment]
Looks good to me, thanks for the updates, and your contribution :)

**Comment by fabfurnari** [comment]
Thanks!

**Pull request merged**
